### ISSUE TITLE
редактор не дает установить бургер на карту http://prntscr.com/chdxyw

### ISSUE THREAD

**Issue by airyng** [airyng/TankGameTest#11]

**Comment by An147** [comment]
Блин, это не баг, это фича!))
А если серьезно, то просто руки пока не дошли. То же самое и с респаунами - надо добавить их в редактор. И перестроить систему респаунов в принципе, а не по 1 респауну на каждый тип танка.

**Comment by airyng** [comment]
типо рандомный тип танков с респа должен выходить?

**Comment by An147** [comment]
Теперь бургер ставится на карту блоком, как и все остальные.
