### ISSUE TITLE
проблема яркости кнопок меню вызываемом esc

### ISSUE THREAD

**Issue by airyng** [airyng/TankGameTest#14]
кнопка перезапуска игры на основной сцене называется "Retire" - очепятка
кнопка перезапуска игры имеет слишком яркий ховер еффект ,из-за чего не видно надписи при наведении.
кнопка возврата в игру не имеет ховер еффекта вообще. нужно привести к общему знаменателю

**Comment by airyng** [comment]
кстати! кнопка Retry предлагает выйти в главное меню, а не пере начать. подозрительная кнопка))

**Comment by airyng** [comment]
я пофикшу

**Comment by An147** [comment]
Не трожь!

**Comment by airyng** [comment]
поздно!
Удален файл GamePausedController. его функция паузы перенесена в MainContextInGameMenu. подкорректированы кнопки в игровом меню. в игровое меню добавлена кнопка паузы

**Comment by airyng** [comment]
запушил
