### ISSUE TITLE
Обновление счетчика жизней

### ISSUE THREAD

**Issue by An147** [airyng/TankGameTest#2]
При подборе голды выпавшей из врага счетчик жизней обновляется, а очки не начисляются

**Comment by airyng** [comment]
погуглил немного про эти евенты, попытался разобраться в твоем коде, но не получилось. возможно имеет смысл вместе подумать. кроме того еще заметил баг с обновлением статы при смерти. такая фигня происходит при самом респауне. конкретно как поправить пока не понял

**Comment by airyng** [comment]
исправлена ошибка когда значение статов обновлялось при спауне игрока.
из-за того, что мы уничтожаем объект игрока, а потом его инстанциируем, у него всегда обновлялись статы. ничего с этим поделать нельзя, так как статы мы храним непосредственно в объекте игрока. было решено при смерти передавать статы в баундери скрипт временного хранилища PlayerStatsRepository , а при спауне забирать отуда статы. теперь все работает. осталась проблема, что можно дойти до минусового значения жизней, при постоянных смертях. исправлю чуть позже

**Comment by airyng** [comment]
теперь если здоровье игрока опускается до нуля, то игра делает reload.level
