### ISSUE TITLE
Замедление от болота иногда не пропадает

### ISSUE THREAD

**Issue by An147** [airyng/TankGameTest#22]
В итоге танк едет медленно, а при попадании в болото вообще ппц как медленно. Баг работает не всегда.

**Comment by airyng** [comment]
нужно понять когда именно) вообще видел его срабатывания, но думал, что пофиксил. по крайней мере уже давно его не видел. ты точно скачал последнюю версию?))

**Comment by An147** [comment]
да, смотри, мне кажется это происходит когда я из одного болота сразу же переезжаю в другое. 
подумай, м.б. этого мы не учли?

**Comment by airyng** [comment]
да, так и есть)) я пофикшу

**Comment by airyng** [comment]
пофикшено
