### ISSUE TITLE
Не работает иммун при респауне (по крайней мере анимация точно)

### ISSUE THREAD

**Issue by An147** [airyng/TankGameTest#23]

**Comment by An147** [comment]
Даже по хоткею иммун анимируется через жопу, а если и анимируется, то по факту не работает. Походу надо учесть сетевой код и давать иммун только на сервере.

**Comment by airyng** [comment]
интересно, что на клиенте(если не хост) имун работает нормально http://prntscr.com/d070xq

**Comment by An147** [comment]
Решено, перенес переменную в PlayerController, т.к. синхронизация требует NetworkIdentity, который м.б. только у рута префаба.
