### ISSUE TITLE
Если боты сдохли от лавы - ничего не выпадает

### ISSUE THREAD

**Issue by An147** [airyng/TankGameTest#28]
Так и должно быть?

**Comment by airyng** [comment]
нуу, надо подумать. 
с одной стороны - нет.
с другой стороны, если боты наступают на лаву, то дамажатся и очень часто дохнут от этого - их смерть не является заслугой плеера.
наверно правильнее всего будет сделать так, что бы боты поворачивали при соприкосновении с лавой, как с другими плотными блоками.

**Comment by airyng** [comment]
исправлено
