### ISSUE TITLE
Очень редкий баг: внезапный респаун

### ISSUE THREAD

**Issue by An147** [airyng/TankGameTest#3]
Вроде бы проявляется при попадании по врагу. Но очень редко.

**Comment by airyng** [comment]
пока не заметил его

**Comment by An147** [comment]
Неужто я просто нечаянно задевал кнопку **R**...

**Comment by airyng** [comment]
скорее всего. предлагаю внимательно за этим следить и если за 2-3 дня такого не повториться, то закрыть тикет

**Comment by airyng** [comment]
прошло 4 дня. очевидно проблема была в кнопке R. закрываю
