### ISSUE TITLE
Откалибровать масштабы блоков

### ISSUE THREAD

**Issue by An147** [airyng/TankGameTest#30]
Путем изменения разрешения текстур...Как бэ ты это вообще прошлепал. Поясню, но не тут, много писать придется.

Кстати, м.б. стоит сделать коллайдер на корабле более точным, он не прямоугольной формы. Думаю, геймплей от этого не пострадает сильно, а наоборот выирает. Например, я сделал баррикаду из 2 кораблей и не могу из нее выстрелить толком - невидимый коллайдер жрет мои снаряды, хотя дырка между кораблями достаточно велика.

**Comment by airyng** [comment]
не проблема, изменю коллайдер корабля на более соответствующий текстуре

**Comment by airyng** [comment]
улучшил колайдер

**Comment by airyng** [comment]
размеры блоков откалиброваны.
настройки размеров блоков для нас необходимы следующие:
350*350 разрешение текстуры
50 pixels per unit у спрайта в юнити
scale префаба 1,1,1
