### ISSUE TITLE
Бешеное ускорение танка

### ISSUE THREAD

**Issue by An147** [airyng/TankGameTest#31]
Когда подобрал бонус ускорения, и задел болото, при выезде из него скорость стала в 2х раза больше нормальной!

**Comment by airyng** [comment]
исправлен баг, когда присмерти в болоте происходило "что то" и повторное вхождение в болото начинало ускорять юнита. дело было в том, что при респауне я возращал скорость танку, а вот флаг замедления в false не переключал
