### ISSUE TITLE
Один из бонусов долго не подбирается

### ISSUE THREAD

**Issue by An147** [airyng/TankGameTest#6]
А потом подбирается при 10м-20м наезде на него.

**Comment by airyng** [comment]
я посмотрю. это какой то конкретный тип бонуса или абсолютно рандомно?

**Comment by airyng** [comment]
10+ тестов не выявили такого бага. буду смотреть далее

**Comment by airyng** [comment]
проблему нашел. оказалось, что при переборе массива юнитов нужно было делать проверку на пустые объекты. у нас же и пустые хранятся сейчас. ошибка возникала при попытке обратиться к несуществующему объекту.
Пофикшено. Закрываю.
