### ISSUE TITLE
Бонус "заморозка" не действует на вновь созданных юнитов

### ISSUE THREAD

**Issue by An147** [airyng/TankGameTest#7]
Зареспавнившиеся юниты на время действия бонуса должны быть тоже заморожены, как и в оригинале игры. Придется создавать какое-то глобальное св-во, например, static переменную класса.

**Comment by airyng** [comment]
ты уверен, что это необходимое введение? сейчас все выглядит логично. я уже придумал, как проще это реализовать, но мне кажется, это не логичным))

**Comment by airyng** [comment]
как выяснилось, работа бонусов будет рассматриваться позднее, так что пока этот вопрос не существенный. закрываю
