### ISSUE TITLE
Не видно, что бы пули команд противников сталкивались друг с другом

### ISSUE THREAD

**Issue by airyng** [airyng/TankGameTest#9]
а нужно ли???

**Comment by An147** [comment]
Нужно, хоть какая-то защита от летящего на тебя стального шторма. Пули точно не сталкиваются, проверял на 50 лайт танках.

**Comment by airyng** [comment]
ок, тогда я разберусь

**Comment by airyng** [comment]
теперь пули команд противников сталкиваются друг с другом и взаимо-уничтожаются
